# .github/workflows/ci.yml

name: CI Pipeline - Build e Teste

# Gatilho: Executa este workflow em qualquer push para branches que não sejam a main
# e em todos os Pull Requests direcionados para a main.
on:
  push:
    branches:
      - '*'           # Todos os branches
      - '!main'       # Exceto o main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # A máquina virtual onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clona o repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use uma versão LTS do Node

      # Passo 3: Instala as dependências do projeto
      - name: Instala as dependências
        run: npm ci # 'ci' é mais rápido e seguro para automação

      # Passo 4: Executa os testes automatizados
      - name: Roda os testes
        run: npm test
